# Global settings. 
dt: 0.02 # s
max_time: 60 # s

# Those settings are global as well but they can be overriden
# individually by each object group below.
pos_bb: [ -0, 60, -10, 10,  0,  10 ]
vel_bb: [ -1,   1,  -1,  1, -1,  1 ]
acc_bb: [ -10,   10,  -10,  10, -10,  10 ]
att_bb: [ -180, 180,  -90,  90, -180, 180 ]
omega_bb: [ -180, 180,  -90,  90, -180, 180 ]
angacc_bb: [ -180, 180,  -90,  90, -180, 180 ]

# Save takeoff and target zone!
exclusion_zone: [[-3, 3, -3, 3, 0, 10], [57, 61, -3, 3, 0, 10]]

density: 0.3 # objects per square meter
scale: [0.2, 0.4]

box_static_region1:
  prefab_name: "rpg_box01"
  traj_type: "cc0000"
  density: 0.21
  pos_bb: [ 0, 60, -10, 10,  0,  0 ]
  scale: [0.2, 0.3]

box_randaccel_region1:
  prefab_name: "rpg_box01"
  traj_type: "ccc0r0"
  density: 0.21
  pos_bb: [ 0, 60, -10, 10,  0,  0 ]
  vel_bb: [ -1,   1,  -1,  1, 0,  0 ]
  acc_bb: [ -0.2,  0.2,  -0.2,  0.2, 0,  0 ]
  scale: [0.2, 0.3]
